# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
    ]
